apiVersion: v1
kind: ReplicationController
metadata:
  name: kuber-rc
spec:
  replicas: 3
  selector:
    app: web-server
  template:
    metadata:
      name: web-echo
      labels:
        app: web-server
    spec:
      containers:
      - name: web-echo-image
        image: fofonovrv/echoserver:alpine
        ports:
        - containerPort: 8000